name: upload to pypi

on:
  release:
    types:
      - created

jobs:

  upload:
    name: upload to pypi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdm twine
    - name: build
      run: pdm build
    - name: upload
      run: twine upload dist/*
      env:
        TWINE_REPOSITORY: pypi
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
